# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwid.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *



class MyButton(QPushButton):
    rightClicked = pyqtSignal()

    def mousePressEvent(self, evt):
        super().mousePressEvent(evt)
        if evt.button()==Qt.RightButton:
            self.rightClicked.emit()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 802)
        MainWindow.setMinimumSize(QtCore.QSize(1002, 802))
        MainWindow.setMaximumSize(QtCore.QSize(1002, 802))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lab_cmd = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd.setGeometry(QtCore.QRect(720, 150, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd.setFont(font)
        self.Lab_cmd.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd.setObjectName("Lab_cmd")
        self.Button_showmove = QtWidgets.QPushButton(self.centralwidget)
        self.Button_showmove.setGeometry(QtCore.QRect(750, 530, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_showmove.setFont(font)
        self.Button_showmove.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_showmove.setObjectName("Button_showmove")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(700, 110, 251, 601))
        self.lineEdit.setStyleSheet("background-color:rgba(154, 229, 204,60);\n"
"border-radius:20px;")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.Button_calc = QtWidgets.QPushButton(self.centralwidget)
        self.Button_calc.setGeometry(QtCore.QRect(750, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_calc.setFont(font)
        self.Button_calc.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_calc.setObjectName("Button_calc")
        self.spinBox_width = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_width.setGeometry(QtCore.QRect(840, 160, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_width.setFont(font)
        self.spinBox_width.setStyleSheet("    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255)")
        self.spinBox_width.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_width.setReadOnly(False)
        self.spinBox_width.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_width.setKeyboardTracking(False)
        self.spinBox_width.setMinimum(3)
        self.spinBox_width.setMaximum(5)
        self.spinBox_width.setObjectName("spinBox_width")
        self.Lab_cmd_2 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_2.setGeometry(QtCore.QRect(720, 200, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_2.setFont(font)
        self.Lab_cmd_2.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_2.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_2.setObjectName("Lab_cmd_2")
        self.spinBox_height = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_height.setGeometry(QtCore.QRect(840, 210, 61, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_height.setFont(font)
        self.spinBox_height.setStyleSheet("    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255)")
        self.spinBox_height.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_height.setReadOnly(False)
        self.spinBox_height.setKeyboardTracking(False)
        self.spinBox_height.setMinimum(3)
        self.spinBox_height.setMaximum(5)
        self.spinBox_height.setObjectName("spinBox_height")
        self.Button_rand = QtWidgets.QPushButton(self.centralwidget)
        self.Button_rand.setGeometry(QtCore.QRect(750, 390, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_rand.setFont(font)
        self.Button_rand.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_rand.setObjectName("Button_rand")
        self.Button_cubic_1 = MyButton(self.centralwidget)
        self.Button_cubic_1.setGeometry(QtCore.QRect(60, 90, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_1.setFont(font)
        self.Button_cubic_1.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_1.setText("")
        self.Button_cubic_1.setObjectName("Button_cubic_1")
        self.Button_cubic_2 = MyButton(self.centralwidget)
        self.Button_cubic_2.setGeometry(QtCore.QRect(180, 90, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_2.setFont(font)
        self.Button_cubic_2.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_2.setText("")
        self.Button_cubic_2.setObjectName("Button_cubic_2")
        self.Button_cubic_3 = MyButton(self.centralwidget)
        self.Button_cubic_3.setGeometry(QtCore.QRect(300, 90, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_3.setFont(font)
        self.Button_cubic_3.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_3.setText("")
        self.Button_cubic_3.setObjectName("Button_cubic_3")
        self.Button_cubic_6 = MyButton(self.centralwidget)
        self.Button_cubic_6.setGeometry(QtCore.QRect(300, 210, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_6.setFont(font)
        self.Button_cubic_6.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_6.setText("")
        self.Button_cubic_6.setObjectName("Button_cubic_6")
        self.Button_cubic_9 = MyButton(self.centralwidget)
        self.Button_cubic_9.setGeometry(QtCore.QRect(300, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_9.setFont(font)
        self.Button_cubic_9.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_9.setText("")
        self.Button_cubic_9.setObjectName("Button_cubic_9")
        self.Button_cubic_8 = MyButton(self.centralwidget)
        self.Button_cubic_8.setGeometry(QtCore.QRect(180, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_8.setFont(font)
        self.Button_cubic_8.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_8.setText("")
        self.Button_cubic_8.setObjectName("Button_cubic_8")
        self.Button_cubic_7 = MyButton(self.centralwidget)
        self.Button_cubic_7.setGeometry(QtCore.QRect(60, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_7.setFont(font)
        self.Button_cubic_7.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_7.setText("")
        self.Button_cubic_7.setObjectName("Button_cubic_7")
        self.Button_cubic_5 = MyButton(self.centralwidget)
        self.Button_cubic_5.setGeometry(QtCore.QRect(180, 210, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_5.setFont(font)
        self.Button_cubic_5.setStyleSheet("QPushButton{\n"
"    background:rgba(255,255,255,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_5.setText("")
        self.Button_cubic_5.setObjectName("Button_cubic_5")
        self.Button_cubic_4 = MyButton(self.centralwidget)
        self.Button_cubic_4.setGeometry(QtCore.QRect(60, 210, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_4.setFont(font)
        self.Button_cubic_4.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_4.setText("")
        self.Button_cubic_4.setObjectName("Button_cubic_4")
        self.Button_cubic_10 = MyButton(self.centralwidget)
        self.Button_cubic_10.setGeometry(QtCore.QRect(420, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_10.setFont(font)
        self.Button_cubic_10.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_10.setText("")
        self.Button_cubic_10.setObjectName("Button_cubic_10")
        self.Button_cubic_11 = MyButton(self.centralwidget)
        self.Button_cubic_11.setGeometry(QtCore.QRect(420, 210, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_11.setFont(font)
        self.Button_cubic_11.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_11.setText("")
        self.Button_cubic_11.setObjectName("Button_cubic_11")
        self.Button_cubic_12 = MyButton(self.centralwidget)
        self.Button_cubic_12.setGeometry(QtCore.QRect(420, 90, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_12.setFont(font)
        self.Button_cubic_12.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_12.setText("")
        self.Button_cubic_12.setObjectName("Button_cubic_12")
        self.Button_cubic_13 = MyButton(self.centralwidget)
        self.Button_cubic_13.setGeometry(QtCore.QRect(540, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_13.setFont(font)
        self.Button_cubic_13.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_13.setText("")
        self.Button_cubic_13.setObjectName("Button_cubic_13")
        self.Button_cubic_14 = MyButton(self.centralwidget)
        self.Button_cubic_14.setGeometry(QtCore.QRect(540, 210, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_14.setFont(font)
        self.Button_cubic_14.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_14.setText("")
        self.Button_cubic_14.setObjectName("Button_cubic_14")
        self.Button_cubic_15 = MyButton(self.centralwidget)
        self.Button_cubic_15.setGeometry(QtCore.QRect(540, 90, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_15.setFont(font)
        self.Button_cubic_15.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_15.setText("")
        self.Button_cubic_15.setObjectName("Button_cubic_15")
        self.Button_cubic_16 = MyButton(self.centralwidget)
        self.Button_cubic_16.setGeometry(QtCore.QRect(180, 450, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_16.setFont(font)
        self.Button_cubic_16.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_16.setText("")
        self.Button_cubic_16.setObjectName("Button_cubic_16")
        self.Button_cubic_17 = MyButton(self.centralwidget)
        self.Button_cubic_17.setGeometry(QtCore.QRect(300, 450, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_17.setFont(font)
        self.Button_cubic_17.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_17.setText("")
        self.Button_cubic_17.setObjectName("Button_cubic_17")
        self.Button_cubic_18 = MyButton(self.centralwidget)
        self.Button_cubic_18.setGeometry(QtCore.QRect(420, 450, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_18.setFont(font)
        self.Button_cubic_18.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_18.setText("")
        self.Button_cubic_18.setObjectName("Button_cubic_18")
        self.Button_cubic_19 = MyButton(self.centralwidget)
        self.Button_cubic_19.setGeometry(QtCore.QRect(60, 450, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_19.setFont(font)
        self.Button_cubic_19.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_19.setText("")
        self.Button_cubic_19.setObjectName("Button_cubic_19")
        self.Button_cubic_20 = MyButton(self.centralwidget)
        self.Button_cubic_20.setGeometry(QtCore.QRect(540, 450, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_20.setFont(font)
        self.Button_cubic_20.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_20.setText("")
        self.Button_cubic_20.setObjectName("Button_cubic_20")
        self.Button_cubic_21 =MyButton(self.centralwidget)
        self.Button_cubic_21.setGeometry(QtCore.QRect(180, 570, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_21.setFont(font)
        self.Button_cubic_21.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_21.setText("")
        self.Button_cubic_21.setObjectName("Button_cubic_21")
        self.Button_cubic_22 = MyButton(self.centralwidget)
        self.Button_cubic_22.setGeometry(QtCore.QRect(300, 570, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_22.setFont(font)
        self.Button_cubic_22.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_22.setText("")
        self.Button_cubic_22.setObjectName("Button_cubic_22")
        self.Button_cubic_23 = MyButton(self.centralwidget)
        self.Button_cubic_23.setGeometry(QtCore.QRect(420, 570, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_23.setFont(font)
        self.Button_cubic_23.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_23.setText("")
        self.Button_cubic_23.setObjectName("Button_cubic_23")
        self.Button_cubic_24 = MyButton(self.centralwidget)
        self.Button_cubic_24.setGeometry(QtCore.QRect(60, 570, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_24.setFont(font)
        self.Button_cubic_24.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_24.setText("")
        self.Button_cubic_24.setObjectName("Button_cubic_24")
        self.Button_cubic_25 = MyButton(self.centralwidget)
        self.Button_cubic_25.setGeometry(QtCore.QRect(540, 570, 120, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_cubic_25.setFont(font)
        self.Button_cubic_25.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_cubic_25.setText("")
        self.Button_cubic_25.setObjectName("Button_cubic_25")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(780, 620, 161, 31))
        self.horizontalSlider.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"}\n"
"QSlider::groove:horizontal { border: 5px solid #999999; height: 5px; margin: 0px 0; left: 5px; right: 5px; }\n"
"QSlider::handle:horizontal { border: 10px ;  width: 15px; margin: -7px -7px -7px -7px; } \n"
"QSlider::add-page:horizontal{ background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #bcbcbc, stop:0.25 #bcbcbc, stop:0.5 #bcbcbc, stop:1 #bcbcbc); }  \n"
"QSlider::sub-page:horizontal{ background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #439cf3, stop:0.25 #439cf3, stop:0.5 #439cf3, stop:1 #439cf3); }")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Lab_cmd_3 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_3.setGeometry(QtCore.QRect(720, 600, 61, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_3.setFont(font)
        self.Lab_cmd_3.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_3.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_3.setObjectName("Lab_cmd_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(780, 293, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255)")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Lab_cmd_4 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_4.setGeometry(QtCore.QRect(703, 287, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_4.setFont(font)
        self.Lab_cmd_4.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_4.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_4.setObjectName("Lab_cmd_4")
        self.Lab_cmd_5 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_5.setGeometry(QtCore.QRect(90, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_5.setFont(font)
        self.Lab_cmd_5.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_5.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_5.setObjectName("Lab_cmd_5")
        self.Lab_Step = QtWidgets.QLabel(self.centralwidget)
        self.Lab_Step.setGeometry(QtCore.QRect(230, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Step.setFont(font)
        self.Lab_Step.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_Step.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_Step.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Step.setObjectName("Lab_Step")
        self.Lab_cmd_7 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_7.setGeometry(QtCore.QRect(330, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_7.setFont(font)
        self.Lab_cmd_7.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_7.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_7.setObjectName("Lab_cmd_7")
        self.Lab_Time = QtWidgets.QLabel(self.centralwidget)
        self.Lab_Time.setGeometry(QtCore.QRect(470, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Time.setFont(font)
        self.Lab_Time.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_Time.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_Time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Lab_Time.setObjectName("Lab_Time")
        self.Lab_cmd_9 = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd_9.setGeometry(QtCore.QRect(40, 710, 631, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd_9.setFont(font)
        self.Lab_cmd_9.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd_9.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd_9.setObjectName("Lab_cmd_9")
        self.lineEdit.raise_()
        self.Lab_cmd.raise_()
        self.Button_showmove.raise_()
        self.Button_calc.raise_()
        self.spinBox_width.raise_()
        self.Lab_cmd_2.raise_()
        self.spinBox_height.raise_()
        self.Button_rand.raise_()
        self.Button_cubic_1.raise_()
        self.Button_cubic_2.raise_()
        self.Button_cubic_3.raise_()
        self.Button_cubic_6.raise_()
        self.Button_cubic_9.raise_()
        self.Button_cubic_8.raise_()
        self.Button_cubic_7.raise_()
        self.Button_cubic_5.raise_()
        self.Button_cubic_4.raise_()
        self.Button_cubic_10.raise_()
        self.Button_cubic_11.raise_()
        self.Button_cubic_12.raise_()
        self.Button_cubic_13.raise_()
        self.Button_cubic_14.raise_()
        self.Button_cubic_15.raise_()
        self.Button_cubic_16.raise_()
        self.Button_cubic_17.raise_()
        self.Button_cubic_18.raise_()
        self.Button_cubic_19.raise_()
        self.Button_cubic_20.raise_()
        self.Button_cubic_21.raise_()
        self.Button_cubic_22.raise_()
        self.Button_cubic_23.raise_()
        self.Button_cubic_24.raise_()
        self.Button_cubic_25.raise_()
        self.horizontalSlider.raise_()
        self.Lab_cmd_3.raise_()
        self.comboBox.raise_()
        self.Lab_cmd_4.raise_()
        self.Lab_cmd_5.raise_()
        self.Lab_Step.raise_()
        self.Lab_cmd_7.raise_()
        self.Lab_Time.raise_()
        self.Lab_cmd_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "重排MN宫"))
        self.Lab_cmd.setText(_translate("MainWindow", "长度"))
        self.Button_showmove.setText(_translate("MainWindow", "显示动画"))
        self.Button_calc.setText(_translate("MainWindow", "计算路径"))
        self.Lab_cmd_2.setText(_translate("MainWindow", "高度"))
        self.Button_rand.setText(_translate("MainWindow", "随机放置数字"))
        self.Lab_cmd_3.setText(_translate("MainWindow", "动画\n"
"速度"))
        self.comboBox.setItemText(0, _translate("MainWindow", "传统A*算法"))
        self.comboBox.setItemText(1, _translate("MainWindow", "速度更快的A*算法"))
        self.comboBox.setItemText(2, _translate("MainWindow", "基于分治的A*算法"))
        self.Lab_cmd_4.setText(_translate("MainWindow", "算法"))
        self.Lab_cmd_5.setText(_translate("MainWindow", "剩余步数："))
        self.Lab_Step.setText(_translate("MainWindow", "0"))
        self.Lab_cmd_7.setText(_translate("MainWindow", "搜索用时："))
        self.Lab_Time.setText(_translate("MainWindow", "0.0s"))
        self.Lab_cmd_9.setText(_translate("MainWindow", "TIPS：在数字放置阶段可以左/右击方格来使得该数字增大/减小"))
